import Head from "next/head";
import Layout from "../components/Layout";
import Banner from "../components/Banner";
import Tcard from "../components/Tcard";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from '../styles/firstpage.module.css'
import SubBanner from "../components/SubBanner";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Component Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Banner />

      <SubBanner />
      <Tcard buttonText="View Project" />
      {/* <Tcard buttonText="View Project" /> */}
    </Layout>
  );
}
